CREATE TABLE Pessoa (
IdPessoa INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NomeCompleto VARCHAR(50) NOT NULL,
Email VARCHAR(40) NOT NULL
)

CREATE TABLE Cliente (
CPF VARCHAR(15) NOT NULL PRIMARY KEY,
Endereço VARCHAR(100) NOT NULL,
Telefone VARCHAR(20) NOT NULL,
Telefone1 VARCHAR(20),
Telefone2 VARCHAR(20),
Telefone3 VARCHAR(20),
Telefone4 VARCHAR(20),
IdPessoa INT IDENTITY(1,1),
FOREIGN KEY(IdPessoa) REFERENCES Pessoa (IdPessoa)
)

CREATE TABLE Usuario2 (
nomeUser VARCHAR(30) NOT NULL PRIMARY KEY,
Senha VARCHAR(30) NOT NULL,
IdPessoa INT identity(1,1),
FOREIGN KEY(IdPessoa) REFERENCES Pessoa (IdPessoa)
)

CREATE TABLE Agenda (
Data DATETIME NOT NULL,
IdAgenda INT IDENTITY(1,1) PRIMARY KEY,
IdPessoa INT NOT NULL,
FOREIGN KEY(IdPessoa) REFERENCES Pessoa (IdPessoa)
)